name: Build

on:
  push:
    branches: [ 'master' ]

jobs:

  build_test_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} for OriumNetwork
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@oriumnetwork'
      - name: Install Dependencies
        run: yarn install
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GHB_TOKEN }}
      - name: Run Smart Contracts unit tests
        run: npx hardhat test
      - name: Publish Package
        run: npm publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GHB_TOKEN }}
